export const bookingStrings = {
  pageTitle: "الحجوزات",
  pageDescription: "إدارة ومتابعة جميع الحجوزات",
  searchPlaceholder: "بحث بالاسم، الهاتف، رقم الحجز...",
  allBookings: "جميع الحجوزات",
  filteredBookings: (label: string) => `الحجوزات - ${label}`,
  noBookings: "لا توجد حجوزات",
  noBookingsDescription: "ستظهر الحجوزات هنا عند إنشائها.",
  noResults: "لا توجد نتائج",
  noResultsDescription: "جرّب تعديل الفلاتر أو مسح البحث.",
  clearFilters: "مسح الفلاتر",
  exportCsv: "تصدير CSV",
  refresh: "تحديث",
  lastUpdated: (time: string) => `آخر تحديث: ${time}`,
  totalBookings: "إجمالي الحجوزات",
  totalValue: "إجمالي قيمة الحجوزات",
  totalValueHint: "لا تشمل الملغاة والمستردة",
  confirmedBookings: "قادمة",
  pendingBookings: "حجوزات قيد الانتظار",
  refundPendingBookings: "في انتظار الاسترداد",
  needsActionBookings: "تحتاج إجراء",
  netCollected: "المحصّل (صافي)",
  refundDueCard: "مستحقات رد",
  statsCaption: (period: string, supplier?: string) =>
    supplier ? `الإحصائيات · ${period} · ${supplier}` : `الإحصائيات · ${period}`,
  allPeriods: "كل الفترات",
  exactStatus: "حالة محددة",
  dateRange: "نطاق تاريخ",
  clearDateRange: "مسح النطاق",
  bookedRevenueHint: (amount: string) => `مُلتزم به: ${amount}`,
  grossMinusRefundHint: (gross: string, refund: string) =>
    `${gross} − ${refund} مستحقات رد`,
  needsActionCount: (n: number) => `${n} تحتاج إجراء`,
  filterByStatus: "تصفية حسب الحالة",
  filterByPayment: "طريقة الدفع",
  filterBySupplier: "المورد",
  filterByTripType: "نوع الرحلة",
  allStatuses: "كل الحالات",
  allPayments: "كل طرق الدفع",
  allSuppliers: "كل الموردين",
  allTripTypes: "كل الأنواع",
  today: "اليوم",
  thisWeek: "هذا الأسبوع",
  thisMonth: "هذا الشهر",
  upcoming: "القادمة",
  customDate: "تاريخ مخصص",
  columns: "أعمدة",
  viewDetails: "عرض التفاصيل",
  customer: "العميل",
  trip: "الرحلة",
  bookingDate: "تاريخ الحجز",
  guests: "الضيوف",
  amount: "المبلغ",
  status: "الحالة",
  payment: "الدفع",
  supplier: "المورد",
  actions: "إجراءات",
  paid: "المدفوع",
  remaining: "المتبقي",
  totalRemaining: "المتبقي للتحصيل",
  declaredAmount: "المبلغ المعلن من العميل",
  declaredAmountHint: "هذا ما قال العميل إنه سيرسله عند الحجز — تحقق من المبلغ الفعلي المستلم قبل التأكيد",
  paymentState: "حالة الدفع",
  allPaymentStates: "كل حالات الدفع",
  paymentHistory: "سجل الدفعات",
  noPaymentHistory: "لا توجد دفعات مسجلة بعد",
  amountReceivedLabel: "المبلغ المستلم فعلياً",
  collectBalance: "تحصيل المتبقي",
  collectBalanceTitle: "تحصيل المبلغ المتبقي؟",
  collectBalanceDescription: "سيتم تسجيل المبلغ كمستلم وإضافته إلى المحفظة.",
  amountToCollectLabel: "المبلغ المحصّل",
  balanceCollected: "تم تحصيل المتبقي بنجاح",
  bookingNumber: "رقم الحجز",
  phone: "رقم الهاتف",
  equipment: "المعدّات",
  quantity: "الكمية",
  adults: "البالغون",
  kids1to6: "أطفال 1–6",
  kids7to12: "أطفال 7–12",
  guestBreakdownMismatch: "مجموع البالغين والأطفال يجب أن يساوي عدد المصريين والأجانب",
  createdAt: "تاريخ الإنشاء",
  guide: "المرشد",
  selectGuide: "اختر مرشد",
  noGuide: "بدون مرشد",
  wantsGuide: "طلب مرشد",
  yes: "نعم",
  no: "لا",
  customerAccount: "حساب العميل",
  technicalDetails: "بيانات تقنية",
  sessionId: "معرف الجلسة",
  orderRef: "رقم الطلب / المرجع",
  userId: "معرف المستخدم",
  tripId: "معرف الرحلة",
  supplierId: "معرف المورد",
  tripDetails: "تفاصيل الرحلة",
  supplierDetails: "تفاصيل المورد",
  paymentDetails: "تفاصيل الدفع",
  bookingDetails: "تفاصيل الحجز",
  manualPaymentActions: "إجراءات الدفع اليدوي",
  confirmPayment: "تأكيد استلام الدفع",
  refundPayment: "استرداد الدفع",
  adminCancel: "إلغاء من الإدارة",
  processRefund: "معالجة الاسترداد",
  confirmPaymentTitle: "تأكيد استلام الدفع؟",
  confirmPaymentDescription:
    "سيتم تأكيد الحجز. أدخل المبلغ الذي استلمته فعلياً عبر إنستاباي — قد يختلف عن المبلغ المعلن.",
  refundPaymentTitle: "استرداد الدفع؟",
  refundPaymentDescription:
    "سيتم استرداد المبلغ للعميل وتحديث حالة الحجز.",
  adminCancelTitle: "إلغاء الحجز من الإدارة؟",
  adminCancelDescription:
    "سيصبح الحجز «في انتظار الاسترداد» دون شرط الـ 24 ساعة. يمكنك بعدها تنفيذ الاسترداد.",
  processRefundTitle: "معالجة الاسترداد",
  processRefundDescription:
    "سيتم إرسال طلب الاسترداد إلى بوابة الدفع. يمكنك إضافة سبب اختياري.",
  noteOptional: "ملاحظة (اختياري)",
  reasonOptional: "السبب (اختياري)",
  cancel: "إلغاء",
  confirm: "تأكيد",
  confirming: "جاري...",
  guideUpdated: "تم تحديث المرشد",
  paymentConfirmed: "تم تأكيد استلام الدفع",
  paymentRefunded: "تم استرداد الدفع",
  refundProcessed: "تمت معالجة الاسترداد بنجاح",
  refundFailed: "فشلت عملية الاسترداد عبر الدفع. راجع حالة الحجز أو حاول لاحقاً.",
  adminCancelSuccess:
    "تم وضع الحجز في انتظار الاسترداد. يمكنك معالجة الاسترداد لاحقاً.",
  loadError: "فشل في تحميل البيانات",
  genericError: "حدث خطأ أثناء تحميل البيانات",
  adminCancelHint:
    "لضيوف بدون حساب أو إلغاء تشغيلي/طقس: ألغِ من الإدارة ليصبح الحجز «في انتظار الاسترداد»، ثم نفّذ الاسترداد.",
  editBooking: "تعديل الحجز",
  editBookingTitle: "تعديل الحجز",
  editBookingDescription: "سيتم إعادة حساب السعر تلقائياً. إذا كان المبلغ المدفوع أكبر من الإجمالي الجديد، سيُخصم الفرق من المحفظة ويُعلَّم الحجز كمسترد مستحق.",
  editBookingLocked: "تسعير هذا الحجز مقفول — يمكن للإدارة فقط تعديل المبلغ يدوياً.",
  saveChanges: "حفظ التعديلات",
  bookingTimeRange: "وقت الحجز يجب أن يكون بين 06:00 و 18:30 بتوقيت القاهرة",
  editSuccess: "تم تحديث الحجز بنجاح",
  supplierCancel: "إلغاء الحجز",
  supplierCancelTitle: "إلغاء الحجز؟",
  supplierCancelDescription: "إذا كان هناك مبلغ مدفوع، سيصبح الحجز في انتظار الاسترداد.",
  supplierCancelSuccess: "تم إلغاء الحجز",
  refundSent: "تم إرسال الاسترداد",
  refundSentTitle: "تأكيد إرسال الاسترداد للعميل؟",
  refundSentDescription: "أكّد أنك أعدت المبلغ المستحق للعميل عبر إنستاباي.",
  refundSentSuccess: "تم تأكيد إرسال الاسترداد",
  adminDelete: "حذف الحجز",
  adminDeleteTitle: "حذف الحجز نهائياً؟",
  adminDeleteDescription:
    "سيُحذف الحجز من كل القوائم والتقارير. لا يمكن التراجع عن هذا الإجراء.",
  adminDeleteTypeToConfirm: "اكتب حذف للتأكيد",
  adminDeleteWalletImpact: (amount: string) => `سيتم خصم ${amount} من محفظة المورد`,
  adminDeleteWarning: "لا يمكن التراجع",
  adminDeleteSuccess: "تم حذف الحجز",
  refundOwed: "مسترد مستحق",
  refundOwedCount: (n: number) => `${n} حجز بمسترد مستحق`,
  priceBefore: "السعر الحالي",
  priceAfter: "السعر الجديد",
  priceDelta: "الفرق",
  refundOwedPreview: "مسترد مستحق للعميل",
  balanceDuePreview: "متبقي على العميل",
  amountOverride: "تعديل المبلغ يدوياً (إدارة)",
  revisionHistory: "سجل التعديلات",
  noRevisions: "لا توجد تعديلات مسجلة",
  durationHours: "المدة (ساعات)",
  note: "ملاحظة",
} as const

export const bookingColumnLabels: Record<string, string> = {
  customer: bookingStrings.customer,
  trip: bookingStrings.trip,
  supplier: bookingStrings.supplier,
  booking_date: bookingStrings.bookingDate,
  guests: bookingStrings.guests,
  amount: bookingStrings.amount,
  remaining: bookingStrings.remaining,
  payment_method: bookingStrings.payment,
  payment_state: bookingStrings.paymentState,
  status: bookingStrings.status,
  actions: bookingStrings.actions,
}
